spring.application.name=spartan
server.port = 8081

// database
spring.datasource.url=jdbc:mysql://localhost:3306/suplements?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysqlPW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
