spring.application.name=spartan
server.port=8081

# Configurações do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/suplements?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=mysqlPW

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect