spring.application.name=spartan
server.port = 8081
spring.datasource.url=jdbc:mysql://localhost:3306/suplements?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysqlPW
spring.jpa.hibernate.ddl-auto=update

